# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabriel Cuendet personal website
email: gabriel.cuendet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Find out more about me! On my personal website you will find my CV, list of
  peer-reviewed publications and links to my social media profiles.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gcuendet.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  gcuendet

# Build settings
markdown: kramdown
